name: Deploy image to Quay.io

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        description: Image Name
        type: string
      image_tag:
        required: true
        description: Image Version
        type: string

env:
  PAYLOAD_IMAGE_NAME: ${{ inputs.image_name }}
  PAYLOAD_IMAGE_TAG: ${{ inputs.image_tag }}
  PAYLOAD_REPOSITORY: ${{ github.repository }}

permissions:
  attestations: write
  id-token: write

jobs:
  deploy_to_quay:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact
          repository: ${{ env.PAYLOAD_REPOSITORY }}
          run-id: ${{ github.run_id}}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate artifact attestation
        id: attest_build_provenance
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: artifact.tar.gz

      - uses: actions/create-github-app-token@v1
        id: app-token
        name: Create GitHub App Token
        with:
          app-id: ${{ vars.CI_APP_ID }}
          private-key: ${{ secrets.CI_APP_PRIVATE_KEY }}
          repositories: quarkiverse-release

      - name: Invoke Deploy to Quay workflow
        run: |
          gh workflow run deploy-quay.yml -R quarkiverse/quarkiverse-release \
            -f image_name=${PAYLOAD_IMAGE_NAME} \
            -f image_tag=${PAYLOAD_IMAGE_TAG} \
            -f github_repository=${GH_REPO} \
            -f run_id=${GH_RUN_ID}
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          GH_REPO: ${{ github.repository }}
          GH_RUN_ID: ${{ github.run_id }}
          ARTIFACT_NAME: ${{ github.event.repository.name }}
